<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- CQRS -->
    <PackageVersion Include="MediatR" Version="14.0.0" />
    <!-- Entity Framework Core -->
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <!-- Authentication & Authorization -->
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="10.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <!-- API -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <!-- Mapping -->
    <PackageVersion Include="AutoMapper" Version="12.0.1" />
    <PackageVersion Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <!-- Development Tools -->
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>
</Project>