export const PUBLIC_ROUTES = {
  HOME: "home",
  LOGIN: "login",
  REGISTER: "register",
  UNAUTHORIZED: "unauthorized",
  NOT_FOUND: "notFound",
};

export const SECURE_ROUTES = {
  DASHBOARD: "dashboard",
  PROFILE: "profile",
  CREATE_FAMILY: "create-family",
  FAMILY_DASHBOARD: "family-dashboard",
  FAMILY_MEMBERS: "family-members",
  ADD_FAMILY_MEMBER: "add-family-member",
  FAMILY_DEPENDENTS: "family-dependents",
  ADD_FAMILY_DEPENDENT: "add-family-dependent",
  FEED_LOGS: "feed-logs",
  ADD_FEED_LOG: "add-feed-log",
  EDIT_FEED_LOG: "edit-feed-log",
  DIAPER_LOGS: "diaper-logs",
  ADD_DIAPER_LOG: "add-diaper-log",
  EDIT_DIAPER_LOG: "edit-diaper-log",
  MEDICINE_LOGS: "medicine-logs",
  ADD_MEDICINE_LOG: "add-medicine-log",
  EDIT_MEDICINE_LOG: "edit-medicine-log",
};

export const ADMIN_ROUTES = {
  DASHBOARD: "dashboard",
  USERS: "users",
  ADD_USER: "add-user",
  EDIT_USER: "edit-user",
  DELETE_USER: "delete-user",
  SETTINGS: "settings",
  FAMILIES: "families",
  ADD_FAMILY: "add-family",
  EDIT_FAMILY: "edit-family",
  FAMILY_USERS: "family-users",
  ADD_FAMILY_MEMBER: "add-family-member",
  DEPENDENTS: "dependents",
  ADD_DEPENDENT: "add-dependent",
  EDIT_DEPENDENT: "edit-dependent",
  DEPENDENT_LOGS: "dependent-logs",
  DIAPER_LOGS: "diaper-logs",
  FEED_LOGS: "feed-logs",
  MEDICINE_LOGS: "medicine-logs",
};
